name: build
on:
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: set-version
        uses: paulhatch/semantic-version@v5.4.0
        id: version
        with:
          tag_prefix: "v"
          version_from_branch: true
          debug: true      
      - name: Print Diagnostic Output
        run: echo "$DEBUG_OUTPUT"
        env:
          DEBUG_OUTPUT: ${{ steps.version.outputs.debug_output }}      