name: build
on:
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: set-version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          version_from_branch: false